export const nutrients = {
  "Energy": {"name": "Energy", "value" : 0, "unit" : "kcal"},
  "Protein": {"name": "Protein", "value" : 0, "unit" : "g"},
  "Total lipid (fat)": {"name": "Fat", "value" : 0, "unit" : "g"},
  "Carbohydrate, by difference": {"name": "Carbs", "value" : 0, "unit" : "g"},
  "Fatty acids, total saturated": {"name": "Saturated Fat", "value" : 0, "unit" : "g"},
  "Fatty acids, total monounsaturated": {"name": "Monounsaturated Fat", "value" : 0, "unit" : "g"},
  "Fatty acids, total polyunsaturated": {"name": "polyunsaturated Fat", "value" : 0, "unit" : "g"},
  "Fatty acids, total trans": {"name": "Trans Fat", "value" : 0, "unit" : "g"},
  "Cholesterol": {"name": "Cholesterol", "value" : 0, "unit" : "mg"},
  "Fiber, total dietary": {"name": "Fiber", "value" : 0, "unit" : "g"},
  "Sugars, total": {"name": "Sugar", "value" : 0, "unit" : "g"},
  "Sodium, Na": {"name": "Sodium", "value" : 0, "unit" : "mg"},
  "Calcium, Ca": {"name": "Calcium", "value" : 0, "unit" : "mg"},
  "Iron, Fe": {"name": "Iron", "value" : 0, "unit" : "mg"},
  "Magnesium, Mg": {"name": "Magnesium", "value" : 0, "unit" : "mg"},
  "Potassium, K": {"name": "Potassium", "value" : 0, "unit" : "mg"},
  "Phosphorus, P": {"name": "Phosphorus", "value" : 0, "unit" : "mg"},
  "Zinc, Zn": {"name": "Zinc", "value" : 0, "unit" : "mg"},
  "Vitamin A, IU": {"name": "Vitamin A", "value" : 0, "unit" : "IU"},
  "Vitamin B-6": {"name": "Vitamin B-6", "value" : 0, "unit" : "mg"},
  "Vitamin B-12": {"name": "Vitamin B-12", "value" : 0, "unit" : "µg"},
  "Vitamin C, total ascorbic acid": {"name": "Vitamin C", "value" : 0, "unit" : "mg"},
  "Vitamin D": {"name": "Vitamin D", "value" : 0, "unit" : "IU"},
  "Niacin": {"name": "Niacin", "value" : 0, "unit" : "mg"},
  "Riboflavin": {"name": "Riboflavin", "value" : 0, "unit" : "mg"},
  "Thiamin": {"name": "Thiamin", "value" : 0, "unit" : "mg"},
  "Caffeine": {"name": "Caffeine", "value" : 0, "unit" : "g"},
  "Water": {"name": "Water", "value" : 0, "unit" : "g"}
};
